### PR TITLE
minimal functional chemical_converion_process.yaml

### PR DESCRIPTION
**Pull request by turbomam**

### CODE REVIEW

**Comment by anastasiyaprymolenna** [comment]
I update the data example to include a representation of a `source_concentration` to reflect the protocol that this was supposed to capture, and show the difference between the two types of concentrations:

> 38. Make 75 μL Digestion Solution by dissolving 4μg trypsin in 75 μL 50mM Ammonium Bicarbonate Solution provided with the FASP Kit to a final concentration of 0.05μg/μL.

**Comment by turbomam** [comment]
Thanks @anastasiyaprymolenna

**Comment by turbomam** [comment]
we should merge in
- https://github.com/microbiomedata/berkeley-schema-fy24/pull/97

**Comment by anastasiyaprymolenna** [comment]
> we should merge in
> 
> * [add proteolyticEnzymeEnum descriptions #97](https://github.com/microbiomedata/berkeley-schema-fy24/pull/97)

agreed. Brynn wanted me to review it at the metadata meeting today first, and then yes we should merge it in!

**Comment by anastasiyaprymolenna** [comment]
Addressing https://github.com/microbiomedata/nmdc-schema/issues/1842

**Comment by anastasiyaprymolenna** [comment]
@picowatt @corilo Please check to make sure the changes to the ChemicalConversionProcess did not leave any relevant information out that could be used to inform workflows.

**Comment by picowatt** [comment]
Superficially these changes don't seem to impact the proteomics workflow with the caveat that what these changes capture is very  much outside of my wheelhouse. @pdpiehowski this one might require you to inspect https://github.com/microbiomedata/berkeley-schema-fy24/pull/100/files.

**Review by SamuelPurvine — APPROVED** [review]

**Review by SamuelPurvine — APPROVED** [review]

**Pull request merged**
