### PR TITLE
Regenerate accidentally-deleted JSON/YAML files in `nmdc_schema` directory

### PR DESCRIPTION
**Pull request by turbomam**
# Guidelines

## _Soft_ Schema Freeze

The `nmdc-schema` and `berkeley-schema-fy24` schemas are under a soft freeze, which means changes **should not** be made that have any downstream implications. To ensure this, all PRs created creating during the freeze will be closely reviewed with **every** component of the NMDC system in mind.

## Reviewers

To ensure no changes are made unexpectedly, PR creators will request reviews from _all_ [Berkeley Schema Roll Out task coordinators](https://docs.google.com/document/d/1XXN1YuaBuSkxPXeiLKm5YxYzXTamBPQrzzeLhlh7PWs/edit#heading=h.u52g8v319adh).

We expect task coordinators to review PRs and provide feedback/approval within 1 week of when they are identified as reviewers. 

PRs will **NOT** be merged until all task coordinators (or one of their delegates) have approved. 

Expedition, questions, and discussion can happen at any meeting.

Delays in review & merging should be addressed in meetings or with NMDC leadership.

# PR Information

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix - the "bug" being that required files were missing
- [ ] Optimization
- [ ] Documentation
- [ ] Schema change: Structure and content
  - created, updated, or deleted a `class`, `slot`, or `enum`
  - changed whether a `slot` is `multivalued`
  - changed the way a `slot` is assigned to a `class`
  - changed the `permissible_values` of an `enum`
  - _etc._
- [ ] Schema change: Cleanup and preparation
  - updated the description of a `class`, `slot`, or `enum`
  - updated the `mappings` of a `class`, `slot`, or `enum` to an ontology
  - added an `enum` for _future_ use (it is not in the `range` of any `slot`)
  - _etc._
     
## Description

In this PR branch, I added JSON and YAML files back into `nmdc_schema/`. 

I added some notes to the issue but haven't written any documentation yet. I could use some help with that, preferably by someone doing a new backmerge with me ASAP. I started one and it was all easy except for conflicts in `nmdc.yaml`.

## Related Issues

- Fixes: https://github.com/microbiomedata/nmdc-schema/issues/2150

## Did you add/update any tests?

- [ ] Yes
- [x] No _(Add a justification below)_
- [ ] I need help with writing tests

Justification: The repo file free is "broken" and I want to fix it ASAP. I or one of my teammates will create a separate ticket about adding a test that would have caught this bug in the future.

## Could this schema change make it so any valid data becomes invalid?

- [ ] Yes _(A migrator is required)_
- [x] No
- [ ] I need help determining this

No migrator is needed. This PR does not change the schema; it just makes the existing schema available in some additional formats.

## If you answered "Yes", does this PR branch include that migrator?

- [ ] Yes
- [ ] No, this PR is incomplete and I need help writing the migrator

## Does this PR have any downstream implications?

- [x] Yes _(Explain below)_
- [ ] No

Explanation: Downstream components that try to access these files will once again be able to access them. Example of such a downstream components is the [refscan](https://github.com/microbiomedata/refscan) tool, whose users sometimes download a copy of one of these YAML files from the repo and then feed that YAML file into the tool.

### CODE REVIEW

**Comment by eecavanna** [comment]
The diff looks good to me—the three missing files were added back in. I assume those were generated from the current versions of their upstream source files located elsewhere in the repo; as opposed to being copy/pasted from a previous commit or archive.

**Comment by eecavanna** [comment]
In the PR description, I see:
> I could use some help with that, preferably by someone doing a new backmerge with me ASAP.

I'd prefer this PR be limited to resolving the issue at hand, and not being combined with another backmerge.

**Comment by eecavanna** [comment]
@turbomam, I have filled out the PR template in this PR except for:
- Tests: When I saw this section/question, it led me to wonder why there is no test that fails when these files are missing
- Description: I mostly copy/pasted the original description into this section. Will you finalize this section?

**Comment by mslarae13** [comment]
Agree with @eecavanna .
Approving from a non-technical side. :)

**Comment by eecavanna** [comment]
This PR has been open for two weeks. Two people have approved it so far.

Looks like the other component representatives were not tagged in it and so may not have been aware that it was open. I will tag them now.


| Component | Representative |
| -- | -- |
| Metadata<br>Schema | @mslarae13 |
| Runtime<br>Mongo database<br>Database migrations | @eecavanna,<br>who will pull in<br>@shreddd as needed |
| Postgres<br>Ingest | @naglepuff |
| Data Portal | @aclum |
| Workflows: MG & MT | @mbthornton-lbl |
| Workflows: MetaB & NOM | @corilo |
| Workflows: LipidO | @kheal |
| Workflows: MetaP | @SamuelPurvine |
| ETL code | @sujaypatil96 |
| Jupyter notebooks | @brynnz22 |

**Review by aclum — APPROVED** [review]

**Pull request merged**
