### PR TITLE
Generate/update derivative files in preparation for packaging the schema

### PR DESCRIPTION
**Pull request by eecavanna**
These files were generated/updated by running this one-liner, when on the tip of `main` (i.e. at commit 36e5db99e37e5e476cdc57c24745a2ef1a0dad9a), with a clean working directory:
```
$ docker compose run --rm app \
  sh -c 'poetry install && make squeaky-clean all test'
```

The file `nmdc.py` was already being tracked by Git. The other 4 files were not. I ran `git add {path/to/file}` for each of those 4 files in order to make it so Git tracks them.

### CODE REVIEW

**Comment by eecavanna** [comment]
Hi @turbomam, during today's metadata meeting, I said I've try to make a build of the Berkeley schema. I ran into a blocker related to GitHub permissions. I do not have permission to merge this PR into the `main` branch. Will you take over from here; i.e. merge this into `main` and generate a GitHub Release?

**Comment by eecavanna** [comment]
I find the title (which I wrote) of this PR to be misleading. The GitHub Actions workflow will run `make squeaky-clean all` ([here](https://github.com/microbiomedata/berkeley-schema-fy24/blob/36e5db99e37e5e476cdc57c24745a2ef1a0dad9a/.github/workflows/pypi-publish.yaml#L35)), so the resulting PyPI package will include the files contained in this PR. The value I see of this PR is, specifically, that it puts those same files into the GitHub repo.

**Review by turbomam — APPROVED** [review]
do you think those git add operations will be remembered now as tracked files?

**Comment by turbomam** [comment]
What permissions would have allowed you to do more of this task, if you wanted to? Here's a current permission table. I think some of those are inherited form the organization. 

```shell
echo -e "login\tadmin\tmaintain\tpull\tpush\ttriage" > berkeley-schema-fy24_permissions.tsv ; \
gh api repos/microbiomedata/berkeley-schema-fy24/collaborators \
--jq '.[] | "\(.login)\t\(.permissions.admin)\t\(.permissions.maintain)\t\(.permissions.pull)\t\(.permissions.push)\t\(.permissions.triage)"' >> berkeley-schema-fy24_permissions.tsv
```

login | admin | maintain | pull | push | triage
-- | -- | -- | -- | -- | --
cmungall | true | true | true | true | true
kfagnan | true | true | true | true | true
scanon | true | true | true | true | true
shreddd | true | true | true | true | true
sierra-moxon | true | true | true | true | true
turbomam | true | true | true | true | true
aclum | false | false | true | true | true
chienchi | false | false | true | true | true
corilo | false | false | true | true | true
dwinston | false | false | true | true | true
GrantFujimoto | false | false | true | true | true
hubin-keio | false | false | true | true | true
jeffbaumes | false | false | true | true | true
kaijli | false | false | true | true | true
kfox1111 | false | false | true | true | true
kheal | false | false | true | true | true
lamccue | false | false | true | true | true
mflynn-lanl | false | false | true | true | true
mhuntemann | false | false | true | true | true
mshakya | false | false | true | true | true
naglepuff | false | false | true | true | true
patrickchain | false | false | true | true | true
PeopleMakeCulture | false | false | true | true | true
picowatt | false | false | true | true | true
poeli | false | false | true | true | true
SamuelPurvine | false | false | true | true | true
Shalsh23 | false | false | true | true | true
simroux | false | false | true | true | true
smcolby | false | false | true | true | true
sujaypatil96 | false | false | true | true | true

**Comment by turbomam** [comment]
I still have some potentially irrational discomfort with omitting generated files form the repo. That has probably played a role in making it hard to make a schema release for a long time now, so as long as you, @pkalita-lbl, @sierra-moxon , @sujaypatil96 can a shared vision on building and deploying, I'll go along with it. 

I may have some scripts that pick some of that stuff up from git raw URLs, but we'll deal with that as it arises.

**Comment by eecavanna** [comment]
>do you think those git add operations will be remembered now as tracked files?

I think so. They are not currently listed in any `.gitignore` files in the repo. I didn't have to do anything more than `git add {filename}` in order to add each one (i.e. no `--force`).

**Comment by eecavanna** [comment]
> What permissions would have allowed you to do more of this task, if you wanted to?

Because I was working after hours, I was blocked by my inability to merge a PR without review. So, being able to override that requirement would have allowed me to do more of this task.

**Comment by eecavanna** [comment]
Closing in favor of https://github.com/microbiomedata/berkeley-schema-fy24/pull/253 (ready for review).

**Pull request closed without merging**
