### PR TITLE
Add values to FileTypeEnum

### PR DESCRIPTION
**Pull request by JamesTessmer**
The goal of this PR is to address issue https://github.com/microbiomedata/nmdc-schema/issues/1958 by adding values to FileTypeEnum.

The value added are:

- Contaminants Amino Acid FASTA
- Analysis Tool Parameter File
- Workflow Operation Summary

created with guidance from @SamuelPurvine.

### CODE REVIEW

**Comment by turbomam** [comment]
I see your review request but this is still in draft status.

**Comment by turbomam** [comment]
I will approve it if you will take it out of draft.

I'm going to be proposing some rules for permissible values in the future, but this is fine given our current informal standards.

**Comment by JamesTessmer** [comment]
@turbomam Ah sorry I forgot to mark it as ready for review, that is done now. Thanks!

**Review by SamuelPurvine — APPROVED** [review]
there's an extra space in the first description :)

**Comment by JamesTessmer** [comment]
> there's an extra space in the first description :)

Removed the space, it seems like everything is ok with everyone so I'll merge this in!

**Pull request merged**
