### PR TITLE
remove AnalyticalSample class from schema

### PR DESCRIPTION
**Pull request by brynnz22**
This PR removes the AnalyticalSample class from the schema. 

Addresses issue https://github.com/microbiomedata/nmdc-schema/issues/1681

### CODE REVIEW

**Review by mslarae13 — APPROVED** [review]
@brynnz22 I did a quick search for AnalyticalSample & it looks like this class is mentioned in 

[notebooks/in-repo-anaggregateds-report.ipynb](https://github.com/microbiomedata/berkeley-schema-fy24/blob/a6954149f0f7df4e2f445882ed9f0d74a7b7e57f/notebooks/in-repo-anaggregateds-report.ipynb#L197)

&
assets/TermsUpdated_organicmatterextraction/TermsUpdated_organicmatterextraction.tsv

I was checking for example files. There are none, so I think this is good to be merged. Just wanted to note the above in the event it mattered for migrtation.

**Comment by brynnz22** [comment]
@turbomam I removed the `AnalyticalSample` rows from the tsv @mslarae13 mentioned, though I am not sure what that tsv is for. As for the notebook: [notebooks/in-repo-anaggregateds-report.ipynb](https://github.com/microbiomedata/berkeley-schema-fy24/blob/a6954149f0f7df4e2f445882ed9f0d74a7b7e57f/notebooks/in-repo-anaggregateds-report.ipynb#L197), `AnalyticalSample` is mentioned as an output of a print statement, so this notebook just needs to be rerun and it shouldn't have `AnalyticalSample` since it is removed from the schema. I could not figure out how to run this notebook in a poetry environment, the import statements don't compute. Since this is just a print statement, do you want me to a) rerun the notebook (if so, can you tell me how I do this with poetry as the dependency management tool?, or b) not worry about it because technically no code is changing?

**Comment by turbomam** [comment]
Thanks for doing that research @mslarae13 and @brynnz22 

I will run the notebook and let you know if I had to do anything tricky. I agree that this is a low risk situation, since the string `AnalyticalSample` only appears as a cached output in the notebook, and not part of any code lines.

As for assets/TermsUpdated_organicmatterextraction/TermsUpdated_organicmatterextraction.tsv ...

**Comment by mslarae13** [comment]
No migration needed IF AnalyticalSample was never used

**Pull request merged**
