### PR TITLE
Add StorageProcess

### PR DESCRIPTION
**Pull request by brynnz22**
Addresses issue: https://github.com/microbiomedata/nmdc-schema/issues/1908

### CODE REVIEW

**Review by anastasiyaprymolenna — APPROVED** [review]
The `StorageProcess` class is in line with the rest of the `MaterialProcessing` classes, and will fulfill the need of capturing the process that samples that samples go through when they are stored in a solution/container before analysis. The data example shows that.

A follow up issue to this PR should include an expansion of the `ContainerCategoryEnum`.

**Comment by anastasiyaprymolenna** [comment]
move slots `contained_in` , `temperature` , `duration` to `MaterialProcessing` instead, so we don't create a separate class.

**Comment by turbomam** [comment]
Thanks for working on this

**Comment by turbomam** [comment]
Does storage satisfy the spirit of the textual description?

> A process that takes one or more samples as inputs and **generates** one or more samples as outputs.

How about the definition of the **broad** mapping to OBI:0000094, 'material processing'

> A planned process which results in physical changes in a specified input material

**Comment by turbomam** [comment]
Maybe storage should be instantiated as a `PlannedProcess` and not a `MaterialProcessing`

**Comment by turbomam** [comment]
In any case, the title of the PR should be changed

**Comment by turbomam** [comment]
Well, my suggestion to instantiate `PlannedProcess` wasn't a solution, since `PlannedProcess` is `abstract`. I'm inclined to say that `MaterialProcessing` should be `abstract`, too. But that doesn't help close this PR.

I would like to move the ownership of `duration` and `temperature` up to `PlannedProcess`. (That doesn't help close this PR either)

**Comment by turbomam** [comment]
I'm still not really happy with the semantics of `MaterialProcess` `contained_in` something. It seems like we're trying to say that something was `contained_in` somethign else during the course of the `MaterialProcess`, or at the end of the `MaterialProcess`

**Comment by turbomam** [comment]
I'm looking for instantiations of `MaterialProcess` or usages of `contained_in` in MongoDB now.

**Comment by turbomam** [comment]
I have a strong urge to say that we should have a `Storage` class, and that it should be a subclass of `PlannedProcess`.

What are the use cases for this class in terms of querying or informing workflows?

**Comment by anastasiyaprymolenna** [comment]
> I have a strong urge to say that we should have a `Storage` class, and that it should be a subclass of `PlannedProcess`.
> 
> What are the use cases for this class in terms of querying or informing workflows?

Did you happen to check out the initial commit on this PR that modeled a "StorageProcess"?

**Comment by anastasiyaprymolenna** [comment]
@mslarae13 Based on the discussion, I think it is best to revert the commit that removed the `StorageProcess` class.

**Comment by mslarae13** [comment]
"spirit"?  I'm not sure what you mean here @turbomam. I think yes? You have 1 or more samples, and when you store them you're noting that it's a stored sample. Is it the generates? Cuz maybe aside from being 'later in time' there may be no changes?
> > Does storage satisfy the spirit of the textual description?
> 
> > > A process that takes one or more samples as inputs and **generates** one or more samples as outputs.

I don't like "results in physical changes" there's not always a physical change. You can air dry your soil and store it for years. The re-use it. 
> 
> How about the definition of the **broad** mapping to OBI:0000094, 'material processing'
> 
> > A planned process which results in physical changes in a specified input material

**Comment by mslarae13** [comment]
> In any case, the title of the PR should be changed

To? "Modify Material Process to account for storage"?

**Comment by mslarae13** [comment]
> I'm still not really happy with the semantics of `MaterialProcess` `contained_in` something. It seems like we're trying to say that something was `contained_in` something else during the course of the `MaterialProcess`, or at the end of the `MaterialProcess`

So, maybe we should put these on processed sample? but we still need something to indicate HOW we go from sample1 to sample2, which requires a process. I don't think NMDC needs the level of granularity that 'stored in' provides as a process. The use of this slot will be to identify "the data from this sample looks weird, oh because they stored it in a plastic that leeches" that's the only use I can find for this field.
So with how NMDC needs to use this metadata, what is the right choice?

**Comment by mslarae13** [comment]
I still disagree with a whole class for storage, because of how NMDC will use this data... It seems like added complication. But I will defer to @cmungall , @sierra-moxon , and @turbomam .

Additional class, or provide slots on existing class.

**Comment by anastasiyaprymolenna** [comment]
A problem from a data retrieval standpoint in moving the slots to MaterialProcesing and not creating a separate class is instantiating an entry for a MaterialProcess to indicate storage is not explicit, all we have to go off of is a material process that used a container for a certain amount of time. Is it good data handling to store data that is specifically indicating storage as an entry of a non-distinct class?

**Comment by anastasiyaprymolenna** [comment]
To do based on metadata meeting

- [ ] provide a slot usage for `substances_used`
- [ ] make this class a child of `PlannedProcess` instead of `MaterialProcessing`
- [ ] use `start_date` instead of `duration`

**Pull request merged**
