### PR TITLE
remove slots from Biosample & DataGeneration & update examples

### PR DESCRIPTION
**Pull request by mslarae13**

### CODE REVIEW

**Comment by mslarae13** [comment]
@aclum I removed [pool_dna_extracts](https://microbiomedata.github.io/nmdc-schema/pool_dna_extracts/) from Biosample. I know we have Class:Pooling. Is there a slot that we could add a close_mapping to? I looked at Pooling, but nothing popped out at me.

**Comment by mslarae13** [comment]
I completed the removal of MIxS slots. i think there's still some slots to be removed, but I'd like Alicia to take a look

**Comment by mslarae13** [comment]
remove seq_method from nucleotide sequencing and alias it for an instance of Class:Instrument

**Comment by mslarae13** [comment]
@turbomam IDK what this failed check means?

**Review by turbomam — APPROVED** [review]

**Comment by brynnz22** [comment]
no migration needed - none of these slots are being used.

**Pull request merged**
