### PR TITLE
getting decisive with exhaustive biosample example

### PR DESCRIPTION
**Pull request by turbomam**
and autoformatting it

### CODE REVIEW

**Comment by turbomam** [comment]
This is an illustration of the state I consider desirable after merging @mslarae13's  PR below. We can merge this in any direction, or just copy this branch's `src/data/valid/Database-biosample-exhasutive.yaml` into `1557-slot-moving-cont`

I can help with merge conflicts, but let's decrease the scope by getting rid of `src/data/typeless/*`

- https://github.com/microbiomedata/berkeley-schema-fy24/pull/42

**Comment by mslarae13** [comment]
Migration to delete these fields from all instances of class Biosample.
These fields should have been moved to materialprocessing or processedsample class

**Comment by turbomam** [comment]
I'm supposed to do some post-hoc QC on this PR, right? I can't remember what it it.

**Comment by mslarae13** [comment]
@turbomam I think the QC was to evaluate if the slots we moved off Biosample exist on any mongo records. To determine if we need to do a migration.

**Comment by brynnz22** [comment]
Removing migration label - none of these slots are used in mongo

**Pull request merged**
