### PR TITLE
fixes to migrator

### PR DESCRIPTION
**Pull request by brynnz22**
Addresses issue: https://github.com/microbiomedata/nmdc-schema/issues/1755

### CODE REVIEW

**Comment by eecavanna** [comment]
These changes look good to me.

Comparing it to the [example migrator](https://github.com/microbiomedata/berkeley-schema-fy24/blob/06ebc00b55401100ca82c4c5a573128cb605e85d/nmdc_schema/migrators/migrator_from_A_B_C_to_X_Y_Z.py#L4):
- [x] class name is now `Migrator`
- [x] `agenda` is now `_agenda` (i.e. a "pseudo-private" variable)

**Comment by brynnz22** [comment]
@eecavanna @turbomam this looks fixed to me. In addition to @eecavanna's list, I also fixed the doc test so `m = Migrator()` (instead of `m=Migrator_from_X_to_PR53()'). It appears to work now when I run `make make-rdf`

**Comment by turbomam** [comment]
thanks! I will try mid day tomorrow at the latest

**Review by eecavanna — APPROVED** [review]
All of the changes look good to me.

**Comment by turbomam** [comment]
running the basic build not, before trying the updated migrator

**Comment by turbomam** [comment]
@eecavanna @brynnz22 I'm sorry you guys had to do more `make-rdf` reverse engineering. Let's review this very briefly when we meet later today.

**Comment by turbomam** [comment]
DO you feel like you understand the advantages and disadvantages of `--selected-collections data_object_set`?

**Comment by turbomam** [comment]
oops, it looks like this branch is using old `pure-export` code

I'll try merging in `main` or pasting in nmdc-schema `main`

```shell
make make-rdf
```

> ```
> rm -rf \
> 	OmicsProcessing.rq \
> 	local/mongo_as_nmdc_database.ttl \
> 	local/mongo_as_nmdc_database_cuire_repaired.ttl \
> 	local/mongo_as_nmdc_database_rdf_safe.yaml \
> 	local/mongo_as_nmdc_database_validation.log \
> 	local/mongo_as_unvalidated_nmdc_database.yaml
> date  # 276.50 seconds on 2023-08-30 without functional_annotation_agg or metaproteomics_analysis_set
> Tue Feb  6 01:19:25 PM EST 2024
> time poetry run pure-export \
> 	--client-base-url https://api.microbiomedata.org \
> 	--endpoint-prefix nmdcschema \
> 	--env-file local/.env \
> 	--max-docs-per-coll 200000 \
> 	--mongo-db-name nmdc \
> 	--mongo-host localhost \
> 	--mongo-port 27777 \
> 	--output-yaml local/mongo_as_unvalidated_nmdc_database.yaml \
> 	--page-size 200000 \
> 	--schema-file src/schema/nmdc.yaml \
> 	--selected-collections activity_set \
> 	--selected-collections biosample_set \
> 	--selected-collections collecting_biosamples_from_site_set \
> 	--selected-collections data_object_set \
> 	--selected-collections extraction_set \
> 	--selected-collections field_research_site_set \
> 	--selected-collections library_preparation_set \
> 	--selected-collections mags_set \
> 	--selected-collections material_sample_set \
> 	--selected-collections metabolomics_analysis_set \
> 	--selected-collections metagenome_annotation_set \
> 	--selected-collections metagenome_assembly_set \
> 	--selected-collections metagenome_sequencing_set  \
> 	--selected-collections metaproteomics_analysis_set \
> 	--selected-collections metatranscriptome_analysis_set \
> 	--selected-collections nom_analysis_set \
> 	--selected-collections omics_processing_set \
> 	--selected-collections planned_process_set \
> 	--selected-collections pooling_set \
> 	--selected-collections processed_sample_set \
> 	--selected-collections read_based_taxonomy_analysis_set \
> 	--selected-collections read_qc_analysis_set \
> 	--selected-collections study_set \
> 	--skip-collection-check
> selected_collections = ('activity_set', 'biosample_set', 'collecting_biosamples_from_site_set', 'data_object_set', 'extraction_set', 'field_research_site_set', 'library_preparation_set', 'mags_set', 'material_sample_set', 'metabolomics_analysis_set', 'metagenome_annotation_set', 'metagenome_assembly_set', 'metagenome_sequencing_set', 'metaproteomics_analysis_set', 'metatranscriptome_analysis_set', 'nom_analysis_set', 'omics_processing_set', 'planned_process_set', 'pooling_set', 'processed_sample_set', 'read_based_taxonomy_analysis_set', 'read_qc_analysis_set', 'study_set')
> Attempting to get 0 documents from nmdcschema/activity_set in pages of 200000.
> warning: 400 Client Error: Bad Request for url: https://api.microbiomedata.org/nmdcschema/activity_set?max_page_size=200000
> warning: FastAPI request to nmdcschema/activity_set appears to have failed. Trying as a PyMongo query.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/mark/gitrepos/berkeley-schema-fy24/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/mark/gitrepos/berkeley-schema-fy24/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/mark/gitrepos/berkeley-schema-fy24/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/mark/gitrepos/berkeley-schema-fy24/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/mark/gitrepos/berkeley-schema-fy24/nmdc_schema/mongo_dump_api_emph.py", line 354, in cli
>     direct_data_all = nmdc_pymongo_client.get_docs_from_pymongo(current_collection, max_docs)
> UnboundLocalError: local variable 'nmdc_pymongo_client' referenced before assignment
> 
> real	0m2.009s
> user	0m0.925s
> sys	0m0.108s
> make: *** [project.Makefile:442: local/mongo_as_unvalidated_nmdc_database.yaml] Error 1
> ```

**Comment by turbomam** [comment]
I intend for the `local/mongo_as_unvalidated_nmdc_database.yaml` target to look like this. I haven't checked that in anywhere.

```make
local/mongo_as_unvalidated_nmdc_database.yaml:
	date  # 276.50 seconds on 2023-08-30 without functional_annotation_agg or metaproteomics_analysis_set
	time $(RUN) pure-export \
		--client-base-url https://api.microbiomedata.org \
		--endpoint-prefix nmdcschema \
		--env-file local/.env \
		--max-docs-per-coll 200000 \
		--mongo-db-name nmdc \
		--mongo-host localhost \
		--mongo-port 27777 \
		--output-yaml $@ \
		--page-size 200000 \
		--schema-file src/schema/nmdc.yaml \
		--selected-collections activity_set \
		--selected-collections biosample_set \
		--selected-collections collecting_biosamples_from_site_set \
		--selected-collections data_object_set \
		--selected-collections extraction_set \
		--selected-collections field_research_site_set \
		--selected-collections library_preparation_set \
		--selected-collections mags_set \
		--selected-collections material_sample_set \
		--selected-collections metabolomics_analysis_set \
		--selected-collections metagenome_annotation_set \
		--selected-collections metagenome_assembly_set \
		--selected-collections metagenome_sequencing_set  \
		--selected-collections metaproteomics_analysis_set \
		--selected-collections metatranscriptome_analysis_set \
		--selected-collections nom_analysis_set \
		--selected-collections omics_processing_set \
		--selected-collections planned_process_set \
		--selected-collections pooling_set \
		--selected-collections processed_sample_set \
		--selected-collections read_based_taxonomy_analysis_set \
		--selected-collections read_qc_analysis_set \
		--selected-collections study_set \
		--skip-collection-check
```

**Comment by turbomam** [comment]
Try swapping in https://raw.githubusercontent.com/microbiomedata/nmdc-schema/main/nmdc_schema/mongo_dump_api_emph.py

**Comment by turbomam** [comment]
Sorry for the delay. The migrator runs nicely now. The output doesn't validate against the berkeley-schema-fy24, but that's to be expected, right?

**Review by turbomam — APPROVED** [review]

**Comment by brynnz22** [comment]
Thanks @turbomam yes, that is to be expected, as long as there aren't errors related to `associated_studies` and `part_of` of the `OmicsProcessing`/`DataGeneration`.

**Pull request merged**
