### PR TITLE
Add additional values to StationaryPhaseEnum

### PR DESCRIPTION
**Pull request by kheal**
These values will be needed for the GC/MS and LC/MS metabolomics process samples.
 
Addresses https://github.com/microbiomedata/nmdc-schema/issues/1909 .

### CODE REVIEW

**Comment by kheal** [comment]
@anastasiyaprymolenna and @brynnz22.  Would you two take a look at this PR and let me know if I'm missing anything with regards to best practices for dev in this repo?

**Review by brynnz22 — APPROVED** [review]
Not sure that two valid examples are necessary since we are just adding a little enum permissible value, but it can't hurt! We also add invalid files to test too, but again, I'm not sure that's necessary since you just added a couple of permissible values to an enumeration. I think this PR looks good! If you really want to flush out the `StationaryPhaseEnum` you could consider adding annotations to the permissible values, like a description, alias, meaning, etc.

**Review by turbomam — APPROVED** [review]

**Comment by turbomam** [comment]
Yes, annotations! I can help.

**Comment by turbomam** [comment]
Here's the LinkML documentation about the slots available for use on a [PermissibleValue](https://linkml.io/linkml-model/latest/docs/PermissibleValue/)

**Comment by turbomam** [comment]
@anastasiyaprymolenna I see that you were intended as a reviewer too. I apologize for merging before you got a chance to comment. Please let me know if you think anything needs to be reverted or changed.

**Pull request merged**
