### PR TITLE
2164 Fix Metatranscriptome Expression class name

### PR DESCRIPTION
**Pull request by aclum**
# Guidelines

## _Soft_ Schema Freeze

The `nmdc-schema` and `berkeley-schema-fy24` schemas are under a soft freeze, which means changes **should not** be made that have any downstream implications. To ensure this, all PRs created during the freeze will be closely reviewed with **every** component of the NMDC system in mind.

## Reviewers

To ensure no changes are made unexpectedly, PR creators will use this PR template to tag and notify all task coordinators. Review should be specifically requested from _all_ [Berkeley Schema Roll Out task coordinators](https://docs.google.com/document/d/1XXN1YuaBuSkxPXeiLKm5YxYzXTamBPQrzzeLhlh7PWs/edit#heading=h.u52g8v319adh) that you expect to be affected by this PR.

We expect task coordinators to review PRs and provide feedback/approval within 1 week of when they are identified as reviewers. 

PRs will **NOT** be merged until all task coordinators (or their delegates) have approved it; either here on GitHub (via "`Review changes` > `Approve`" or an equivalent comment) or verbally.

Expedition, questions, and discussion can happen at any meeting.

Delays in review & merging should be addressed in meetings or with NMDC leadership.

| If you expect the changes to<br>impact this component... | ...[request a review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review)<br>from this person |
| -- | -- |
| Metadata<br>Schema | @mslarae13 |
| Runtime<br>Mongo database<br>Database migrations | @eecavanna,<br>who will pull in<br>@shreddd as needed |
| Postgres<br>Ingest | @naglepuff |
| Data Portal | @aclum |
| Workflows: MG & MT | @mbthornton-lbl |
| Workflows: MetaB & NOM | @corilo |
| Workflows: LipidO | @kheal |
| Workflows: MetaP | @SamuelPurvine |
| ETL code | @sujaypatil96 |
| Jupyter notebooks | @brynnz22 |

# PR Information

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation
- [ ] Schema change: Structure and content
  - created, updated, or deleted a `class`, `slot`, or `enum`
  - changed whether a `slot` is `multivalued`
  - changed the way a `slot` is assigned to a `class`
  - changed the `permissible_values` of an `enum`
  - _etc._
- [ ] Schema change: Cleanup and preparation
  - updated the description of a `class`, `slot`, or `enum`
  - updated the `mappings` of a `class`, `slot`, or `enum` to an ontology
  - added an `enum` for _future_ use (it is not in the `range` of any `slot`)
  - _etc._
     
## Description

> _PRs should be [small and concise](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/best-practices-for-pull-requests#write-small-prs)._
>
> Aim to create small, focused pull requests that fulfill a single purpose. Smaller pull requests are easier and faster to review and merge, leave less room to introduce bugs, and provide a clearer history of changes.

This PR fixes an issue with a previous backmerge which did not keep the correct changes for replacing [MetatranscriptomeAnalysis](https://microbiomedata.github.io/berkeley-schema-fy24/MetatranscriptomeAnalysis/) with MetatranscriptomeExpressionAnalysis. 
This PR also updates permissible values for FailureWhereEnum.

## Related Issues

> All PRs should relate to or fix an issue(s). Please identify the issue(s) below.

- Related Issue(s): #
- Fixes: https://github.com/microbiomedata/nmdc-schema/issues/2164

## Did you add/update any tests?

- [x] Yes
- [ ] No _(Add a justification below)_
- [ ] I need help with writing tests

## Could this schema change make it so any valid data becomes invalid?

> This is a question about what the schema allows. It is not a question about what happens to exists in the NMDC database right now.
> 
> Example: If, in this PR branch, you renamed a `slot` from `foo` to `foo_bar`, the answer to this question would be "yes," **even if** nothing in the NMDC database _currently_ uses the `foo` `slot`.
>
> More examples: `slot` or `class` name changes, changes to a `slot`'s `multivalued` state, changes to a `slot`'s `range` (e.g. string to integer), changes to `slot` assignments to `class`es, changes to an `enum`'s `permissible_values`

- [ ] Yes _(A migrator is required)_
- [ ] No
- [x] I need help determining this
@eecavanna please check the existing migrators to make sure the correct new class name is used.

## If you answered "Yes", does this PR branch include that migrator?

- [ ] Yes
- [ ] No, this PR is incomplete and I need help writing the migrator

## Does this PR have any downstream implications?

> Examples: any change here that requires a change to workflows, workflow automation, the Mongo-to-Postgres ingest process, Jupyter notebooks, the Runtime, etc.

- [x] Yes _(Explain below)_
- [ ] No

I caught this when working on migrating workflow_automation code. I believe we should proceed with this fix so we can use the correct class. It is very small to update to the correct class names.

### CODE REVIEW

**Review by mbthornton-lbl — APPROVED** [review]

**Comment by aclum** [comment]
It doesn't look like eric's last migrator needs to be changed, that just pertains to Database slot names but someone will need to check the migrators. If needed I can add a dummy record to dev so that @eecavanna  can run the migrators to confirm that the record ends up in the workflow_execution_set with the correct type assignment.

**Review by brynnz22 — APPROVED** [review]
Looks good to me!

**Review by turbomam — APPROVED** [review]

**Comment by eecavanna** [comment]
I'll write a migrator to go along with this schema change. @aclum confirmed there is no data currently in our Mongo database that would be affected. I want to account even for hypothetical documents (because someone might apply this schema change to a different instance of the NMDC database, at a different time, and there might be relevant documents in that situation).

ETA is: this sprint.

**Comment by aclum** [comment]
@aclum  change failure where
@eecavanna to write a migrator in this PR.

**Comment by kheal** [comment]
> I'll write a migrator to go along with this schema change. @aclum confirmed there is no data currently in our Mongo database that would be affected. I want to account even for hypothetical documents (because someone might apply this schema change to a different instance of the NMDC database, at a different time, and there might be relevant documents in that situation).
> 
> ETA is: this sprint.

FYI @eecavanna I think just changing the references of MetatranscriptomeAnalysis to MetatranscriptomeExpressionAnalysis in parts 10 and 12 of the Berkeley migrators will take care of this.

**Comment by aclum** [comment]
@kheal @SamuelPurvine @mslarae13  I made sure all DataGeneration and WorkflowExecution subclasses were permissible values in FailureWhereEnum. Please check to see if any [MaterialProcessing classes](https://microbiomedata.github.io/berkeley-schema-fy24/MaterialProcessing/) are missing where if the analysis looks bad you can track it back to a MaterialProcessing class. For example, in sequencing if a lot of data is removed because of adapter hits that the root cause is LIbraryPrepration.

**Comment by SamuelPurvine** [comment]
> @kheal @SamuelPurvine @mslarae13 I made sure all DataGeneration and WorkflowExecution subclasses were permissible values in FailureWhereEnum. Please check to see if any [MaterialProcessing classes](https://microbiomedata.github.io/berkeley-schema-fy24/MaterialProcessing/) are missing where if the analysis looks bad you can track it back to a MaterialProcessing class. For example, in sequencing if a lot of data is removed because of adapter hits that the root cause is LIbraryPrepration.

All 9 'MaterialProcessing` (sub)classes are in the `FailureCategorization` class... I'm not really sure we are "doing" failure categorization tracking for proteomics, but then this is kind of the first time I've read it was being done at all :) I suppose the use case is samples were collected, sent to EMSL (or processed wherever), data were collected on instrument, and immediately slurped into NMDC for processing, whereupon we find there "aren't enough results", and we want to track back to see what might have gone wrong? Hard to say how/where we would start enumerating/describing all the things that could go wrong! Future work, one supposes...

Anyway, this seems like a fine PR, shouldn't have downstream affects on proteomics

**Review by mslarae13 — COMMENTED** [review]
discussed at wed 1pm metadata meeting.
From that discussion this LGTM.
No technical comments.

**Review by kheal — APPROVED** [review]

**Comment by kheal** [comment]
> @kheal @SamuelPurvine @mslarae13 I made sure all DataGeneration and WorkflowExecution subclasses were permissible values in FailureWhereEnum. Please check to see if any [MaterialProcessing classes](https://microbiomedata.github.io/berkeley-schema-fy24/MaterialProcessing/) are missing where if the analysis looks bad you can track it back to a MaterialProcessing class. For example, in sequencing if a lot of data is removed because of adapter hits that the root cause is LIbraryPrepration.

@aclum.  I think the DataGeneration and WorkflowExecution subclasses are the potentially trackable ones for the mass-spec omcis.  I don't anticipate being able to track failures back to specific  MaterialProcessing steps so no need to include any additional subclasses for that ABC. Good idea to include MassSpectrometry.

**Review by eecavanna — APPROVED** [review]
Thanks, @kheal and @brynnz22, for the guidance about the migrator changes!

I made these two changes today:
1. The `part_10` migrator now sets the `type` value of each document in the `metatranscriptome_analysis_set` collection to `nmdc:MetatranscriptomeExpressionAnalysis` instead of `nmdc:MetatranscriptomeAnalysis`.
2. The `part_12` migrator now populates the `qc_failure_where` field with `MetatranscriptomeExpressionAnalysis` whenever it would have previously populated it with `MetatranscriptomeActivity`.

I'm comfortable with this PR being merged in.

**Pull request merged**
