### PR TITLE
1525 add slots to material processing classes that were on omics processing

### PR DESCRIPTION
**Pull request by mslarae13**
nucl_acid_ext exists on OmicsProcessing (DataGeneration) and Biosample

This PR is adding MIXS slot nucl_acid_ext as a narrow_mapping for extraction_method and extraction_target as it's providing BOTH
This PR also adds http://purl.obolibrary.org/obo/NCIT_C177560 as a narrow_mapping for both extraction_method and extraction_target as this is also a more specific way of identifying BOTH.

### CODE REVIEW

**Comment by anastasiyaprymolenna** [comment]
@aclum  extraction_method slot on Class:Extraction needs to reviewed. We should get rid of it if it is not being used because the enum it is using is shared with extraction_target so it is not informative.

**Comment by mbthornton-lbl** [comment]
All wrong try again

**Comment by aclum** [comment]
@anastasiyaprymolenna see example data https://github.com/microbiomedata/nmdc-schema/blob/main/src/data/valid/Database-nucleic-extraction.yaml
extraction_method was intended to store some short string to summarize how the extraction was done, it is not intended to specify what the target (DNA, RNA) to extract is.

**Review by aclum — APPROVED** [review]

**Comment by brynnz22** [comment]
no migration

**Pull request merged**
